# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04yolo\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\"#\n\x12\x44\x65tectBatchRequest\x12\r\n\x05\x62\x61tch\x18\x01 \x03(\x0c\"8\n\x0e\x44\x65tectResponse\x12&\n\x07objects\x18\x01 \x03(\x0b\x32\x15.yolo.ObjectDetection\"=\n\x13\x44\x65tectBatchResponse\x12&\n\x08requests\x18\x01 \x03(\x0b\x32\x14.yolo.DetectResponse\"n\n\x0fObjectDetection\x12\x1e\n\x05\x63lass\x18\x01 \x01(\x0e\x32\x0f.yolo.ClassEnum\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\'\n\x0c\x62ounding_box\x18\x03 \x01(\x0b\x32\x11.yolo.BoundingBox*\xa2\x01\n\tClassEnum\x12\x0e\n\nLIVEL_KNOT\x10\x00\x12\x0e\n\nDEATH_KNOT\x10\x01\x12\x10\n\x0cKNOT_MISSING\x10\x02\x12\x13\n\x0fKNOT_WITH_CRACK\x10\x03\x12\t\n\x05\x43RACK\x10\x04\x12\r\n\tQUARTZITY\x10\x05\x12\t\n\x05RESIN\x10\x06\x12\n\n\x06MARROW\x10\x07\x12\x0e\n\nBLUE_STAIN\x10\x08\x12\r\n\tOVERGROWN\x10\t2N\n\x04Yolo\x12\x46\n\rDetectObjects\x12\x18.yolo.DetectBatchRequest\x1a\x19.yolo.DetectBatchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CLASSENUM']._serialized_start=366
  _globals['_CLASSENUM']._serialized_end=528
  _globals['_BOUNDINGBOX']._serialized_start=20
  _globals['_BOUNDINGBOX']._serialized_end=93
  _globals['_DETECTBATCHREQUEST']._serialized_start=95
  _globals['_DETECTBATCHREQUEST']._serialized_end=130
  _globals['_DETECTRESPONSE']._serialized_start=132
  _globals['_DETECTRESPONSE']._serialized_end=188
  _globals['_DETECTBATCHRESPONSE']._serialized_start=190
  _globals['_DETECTBATCHRESPONSE']._serialized_end=251
  _globals['_OBJECTDETECTION']._serialized_start=253
  _globals['_OBJECTDETECTION']._serialized_end=363
  _globals['_YOLO']._serialized_start=530
  _globals['_YOLO']._serialized_end=608
# @@protoc_insertion_point(module_scope)
